## **Tutorial 1**

In [1]:
import numpy as np

myarr = np.array([[1, 2, 3, 4, 5]], np.int64)
print(myarr[0])
myarr[0,1]


[1 2 3 4 5]


2

In [2]:
myarr.shape

(1, 5)

In [3]:
myarr[0,1]

2

# **Array creation from other python structures** #

In [4]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
listarray.size

9

In [7]:
listarray.dtype

dtype('int32')

In [8]:
listarray.shape

(3, 3)

In [9]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [10]:
zeros = np.zeros((3,3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
rng = np.arange(21)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])