## **Tutorial 1**

In [1]:
import numpy as np

myarr = np.array([[1, 2, 3, 4, 5]], np.int64)
print(myarr[0])
myarr[0,1]


[1 2 3 4 5]


2

In [2]:
myarr.shape

(1, 5)

In [3]:
myarr[0,1]

2

# **Array creation from other python structures** #

In [4]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
listarray.size

9

In [7]:
listarray.dtype

dtype('int32')

In [8]:
listarray.shape

(3, 3)

In [9]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [10]:
zeros = np.zeros((3,3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
rng = np.arange(21)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
lspace = np.linspace(1,20,11)

In [15]:
lspace

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

In [16]:
ide = np.identity(49)

In [17]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [18]:
ide.shape

(49, 49)

In [19]:
ide.size

2401

In [20]:
axr = np.arange(85)

In [21]:
axr = axr.reshape(5,17)
axr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84]])

In [22]:
axr.shape

(5, 17)

In [23]:
axr = axr.ravel()

In [24]:
axr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [25]:
axr.shape

(85,)

In [26]:
x = [[1,2,3],[4,5,6],[8,9,1]]
azr = np.array(x)

In [27]:
azr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 1]])

In [28]:
azr.sum(axis=0)

array([13, 16, 10])

In [29]:
azr.sum(axis=1)

array([ 6, 15, 18])