## **Tutorial 1**

In [80]:
import numpy as np
myarr = np.array([[1, 2, 3, 4, 5]], np.int64)
print(myarr[0])
myarr[0,1]


[1 2 3 4 5]


2

In [81]:
myarr.shape

(1, 5)

In [82]:
myarr[0,1]

2

# **Array creation from other python structures** #

In [83]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [84]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
listarray.size

9

In [86]:
listarray.dtype

dtype('int32')

In [87]:
listarray.shape

(3, 3)

In [88]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

# **Intrinsic NumPy array creation**

In [89]:
zeros = np.zeros((3,3))

In [90]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
rng = np.arange(21)

In [92]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [93]:
lspace = np.linspace(1,20,11)

In [94]:
lspace

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

In [95]:
ide = np.identity(49)

In [96]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [97]:
ide.shape

(49, 49)

In [98]:
ide.size

2401

In [99]:
axr = np.arange(85)

In [100]:
axr = axr.reshape(5,17)
axr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84]])

In [101]:
axr.shape

(5, 17)

In [102]:
axr = axr.ravel()

In [103]:
axr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [104]:
axr.shape

(85,)

In [105]:
x = [[1,2,3],[4,5,6],[8,9,1]]
azr = np.array(x)

In [106]:
azr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 1]])

In [107]:
azr.sum(axis=0)

array([13, 16, 10])

In [108]:
azr.sum(axis=1)

array([ 6, 15, 18])

In [131]:
apr = azr.T
apr

array([[1, 4, 8],
       [2, 5, 9],
       [3, 6, 1]])

In [110]:
azr.flat

In [111]:
for item in azr.flat:
    print(item)

1
2
3
4
5
6
8
9
1


In [112]:
azr.ndim

2

In [113]:
azr.size

9

In [114]:
azr.nbytes

36

In [115]:
azr.argmax()

7

In [116]:
azr.argmin()

0

In [117]:
arx = np.array([1,8,4,3,98,34])
arx.argsort()

array([0, 3, 2, 1, 5, 4], dtype=int64)

In [118]:
azr.argmin()

0

In [119]:
azr.argmax()

7

In [121]:
azr.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [122]:
azr.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [123]:
azr.argmin(axis=0)

array([0, 0, 2], dtype=int64)

In [124]:
azr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [125]:
azr.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [126]:
azr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [127]:
azr.ravel()

array([1, 2, 3, 4, 5, 6, 8, 9, 1])

In [129]:
azr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [8],
       [9],
       [1]])

In [132]:
azr + apr

array([[ 2,  6, 11],
       [ 6, 10, 15],
       [11, 15,  2]])

In [133]:
azr * apr

array([[ 1,  8, 24],
       [ 8, 25, 54],
       [24, 54,  1]])